# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('topic', models.TextField()),
                ('purpose', models.TextField()),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestap', models.DateTimeField()),
                ('text', models.TextField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Channel')),
                ('file_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.File')),
            ],
        ),
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('color', models.CharField(max_length=6)),
                ('real_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.SUser'),
        ),
    ]
