# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20170313_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
